### ISSUE TITLE
no coreutils?

### ISSUE THREAD

**Issue by puddingepoch** [t184256/nix-on-droid#31] opened 2019-12-26 04:07 UTC
when i run home setup, it states its installed core utils

but i cannot use any coreutrils, grep, which, sed, etc are not found 

and there is 0 documentation to speak of so can i please get some answers im trying to setup x11

**Comment by t184256** [comment] 2019-12-26 11:55
Please remove data, start the installation again, try a few commands and then copy-paste and post the whole output so that I can see what feet wrong.

Regarding X11 and documentation, this is not as polished as Termux or others. You could be the first to do it, to you can write it =) Might be possible with a VNC server and a client like bVNC, but I'm not sure.

**Comment by puddingepoch** [comment] 2020-01-01 20:20
uhhh i can find no way to install the x11 repos and such so no not really not possible
what output? its just command not found as if it were not installed

**Comment by t184256** [comment] 2020-01-01 20:25
There are no separate "X11 repos" for nixpkgs. I'd try to install some VNC server, start it, connect to it with a VNC client like bVNC, export `DISPLAY` environment variable, install some simple X11 app like leafpad and try to run it.

What exactly did you try? What errors do you get?

**Comment by t184256** [comment] 2020-01-01 20:27
By `post the whole output` I meant copy-pasting the whole terminal output since the beginning of installation and posting it to pastebin or gist.github.com

**Comment by Gerschtli** [comment] 2020-01-01 20:29
Can you please be more explicit on what commands exactly you executed? Because I cannot reproduce that coreutils is not installed.

For the x11 problem: What commands did you execute and what are the errors printed to your console? Maybe there are patches necessary to be compliant with the android environment.

The more information you can provide, the better we can help you. With the currently provided information we are not able to give you hints regarding the cause of the problem.

**Comment by avalenn** [comment] 2020-05-01 20:22
Same thing here with nix-on-droid 0.66_v0.2.2_nix from f-droid. Install transcript attached.
[nix-transcript.txt](https://github.com/t184256/nix-on-droid/files/4566168/nix-transcript.txt)

**Comment by t184256** [comment] 2020-05-01 21:31
@avalenn, this is, actually, intended. `grep` or `sed` aren't part of coreutils and are not installed by default. Please uncomment the corresponding lines in `~/.config/nixpkgs/nix-on-droid.nix` and execute `Nix-on-Droid switch` to install them.

**Comment by avalenn** [comment] 2020-05-02 09:47
I found what you said just after commenting. One troubling thing is that login bash seems to be very minimal (no interactive line editing, some options lacking...) but an `exec bash` solves it.

And I wonder where is `which` as I was sure it was in coreutils *and* a bash builtin and it seems it is in neither :-( At least `whereis` was in util-linux

**Comment by t184256** [comment] 2020-05-02 13:55
> One troubling thing is that login bash seems to be very minimal (no interactive line editing, some options lacking...) but an exec bash solves it.

True. I knew about this issue, but thought it was pretty minor. Should be fixed in b481807.

> And I wonder where is which as I was sure it was in coreutils and a bash builtin and it seems it is in neither :-( At least whereis was in util-linux

Which is in `which`. Bash has `command -v`.

**Closed** 2020-05-07 15:53 UTC
